spring:
  application:
    name: issue_tracker
  profiles:
    active: dev
---

spring:
    config:
      activate:
            on-profile: dev
      import: classpath:db-config.yml

---

spring:
    config:
      activate:
            on-profile: test
      import: classpath:test-db-config.yml