spring:
  application:
    name: issue_tracker
  profiles:
    active: dev

logging:
  level:
    org.springframework.jdbc.core: INFO

---

spring:
    config:
      activate:
            on-profile: dev
      import: classpath:db-config.yml