 spring:
   datasource:
    url: 'jdbc:h2:mem:issue_test_db'
    username: 'sa'
    password: ''
    driver-class-name: 'org.h2.Driver'

   sql:
     init:
       schema-locations: classpath:sql/ddl.sql
#       data-locations: classpath:sql/data.sql
       mode: always